/**
 * Language Configuration
 * Provides a comprehensive list of languages supported by Tesseract.js.
 * Each object contains the language name for the UI and the corresponding Tesseract code.
 */
export const languages = [
    { code: 'eng', name: 'English' },
    { code: 'fas', name: 'Persian (Farsi)' },
    { code: 'ara', name: 'Arabic' },
    { code: 'afr', name: 'Afrikaans' },
    { code: 'amh', name: 'Amharic' },
    { code: 'aze', name: 'Azerbaijani' },
    { code: 'bel', name: 'Belarusian' },
    { code: 'ben', name: 'Bengali' },
    { code: 'bul', name: 'Bulgarian' },
    { code: 'cat', name: 'Catalan' },
    { code: 'ces', name: 'Czech' },
    { code: 'chi_sim', name: 'Chinese (Simplified)' },
    { code: 'chi_tra', name: 'Chinese (Traditional)' },
    { code: 'dan', name: 'Danish' },
    { code: 'deu', name: 'German' },
    { code: 'ell', name: 'Greek' },
    { code: 'est', name: 'Estonian' },
    { code: 'fin', name: 'Finnish' },
    { code: 'fra', name: 'French' },
    { code: 'gle', name: 'Irish' },
    { code: 'guj', name: 'Gujarati' },
    { code: 'heb', name: 'Hebrew' },
    { code: 'hin', name: 'Hindi' },
    { code: 'hrv', name: 'Croatian' },
    { code: 'hun', name: 'Hungarian' },
    { code: 'hye', name: 'Armenian' },
    { code: 'ind', name: 'Indonesian' },
    { code: 'isl', name: 'Icelandic' },
    { code: 'ita', name: 'Italian' },
    { code: 'jpn', name: 'Japanese' },
    { code: 'kan', name: 'Kannada' },
    { code: 'kat', name: 'Georgian' },
    { code: 'kor', name: 'Korean' },
    { code: 'kur', name: 'Kurdish' },
    { code: 'lat', name: 'Latin' },
    { code: 'lav', name: 'Latvian' },
    { code: 'lit', name: 'Lithuanian' },
    { code: 'mal', name: 'Malayalam' },
    { code: 'mar', name: 'Marathi' },
    { code: 'mkd', name: 'Macedonian' },
    { code: 'mlt', name: 'Maltese' },
    { code: 'msa', name: 'Malay' },
    { code: 'nep', name: 'Nepali' },
    { code: 'nld', name: 'Dutch' },
    { code: 'nor', name: 'Norwegian' },
    { code: 'pol', name: 'Polish' },
    { code: 'por', name: 'Portuguese' },
    { code: 'ron', name: 'Romanian' },
    { code: 'rus', name: 'Russian' },
    { code: 'slk', name: 'Slovak' },
    { code: 'slv', name: 'Slovenian' },
    { code: 'spa', name: 'Spanish' },
    { code: 'sqi', name: 'Albanian' },
    { code: 'srp', name: 'Serbian' },
    { code: 'swe', name: 'Swedish' },
    { code: 'tam', name: 'Tamil' },
    { code: 'tel', name: 'Telugu' },
    { code: 'tha', name: 'Thai' },
    { code: 'tur', name: 'Turkish' },
    { code: 'ukr', name: 'Ukrainian' },
    { code: 'urd', name: 'Urdu' },
    { code: 'vie', name: 'Vietnamese' },
    // Add more languages as needed
];
